### ISSUE TITLE
s2_buffer issue

### ISSUE THREAD

**Issue by edzer** [r-spatial/s2#106]
I know this is w.i.p., but ran into this:
```r
library(sf)                                                                           
# Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
nc = read_sf(system.file("gpkg/nc.gpkg", package="sf"))
sf_use_s2(TRUE)                                                                       
b = st_buffer(st_geometry(nc), 0.1)       

#  *** caught segfault ***
# address (nil), cause 'memory not mapped'

# Traceback:
#  1: cpp_s2_buffer_cells(recycled[[1]], recycled[[2]], max_cells,     min_level)
#  2: new_s2_xptr(cpp_s2_buffer_cells(recycled[[1]], recycled[[2]],     max_cells, min_level), "s2_geography")
#  3: s2::s2_buffer_cells(x, dist, ...)
#  4: st_as_sfc(s2::s2_buffer_cells(x, dist, ...), crs = st_crs(x))
#  5: st_buffer.sfc(st_geometry(nc), 0.1)
#  6: st_buffer(st_geometry(nc), 0.1)
# An irrecoverable exception occurred. R is aborting now ...
```
gdb backtrace:
```
gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007fffe81c6fb5 in Op::processFeature (this=this@entry=0x7ffffffe0e40, feature=..., i=i@entry=0)
    at /home/edzer/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include/RcppCommon.h:92
#2  0x00007fffe81cc6c8 in UnaryGeographyOperator<Rcpp::Vector<19, Rcpp::PreserveStorage>, SEXPREC*>::processVector (this=this@entry=0x7ffffffe0e40, geog=...)
    at /home/edzer/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include/RcppCommon.h:111
#3  0x00007fffe81c5088 in cpp_s2_buffer_cells (geog=..., distance=..., maxCells=maxCells@entry=1000, minLevel=minLevel@entry=-1)
    at /home/edzer/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include/Rcpp/vector/traits.h:65
#4  0x00007fffe81db529 in _s2_cpp_s2_buffer_cells (geogSEXP=0x555559fcdd90, distanceSEXP=<optimized out>, maxCellsSEXP=<optimized out>, minLevelSEXP=<optimized out>)
    at /home/edzer/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include/Rcpp/as.h:151
```

**Comment by edzer** [comment]
This now works; closing.
